# Generated by Django 4.2.2 on 2023-07-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PastQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Session", models.CharField(max_length=100)),
                ("Lecturer_name", models.CharField(max_length=100)),
                ("Course_name", models.CharField(max_length=100)),
                ("Course_title", models.CharField(max_length=100)),
                (
                    "Course_file",
                    models.FileField(upload_to="media/resources/past-question/"),
                ),
                ("Course_image", models.ImageField(upload_to="media/resources/images")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Session", models.CharField(max_length=100)),
                ("Topic", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
                ("Supervisor", models.CharField(max_length=100)),
                (
                    "Project_file",
                    models.FileField(upload_to="media/resources/project/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
                (
                    "TextBook_file",
                    models.FileField(upload_to="media/resources/text-book/"),
                ),
            ],
        ),
    ]
