# Generated by Django 4.2.2 on 2023-07-16 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Session",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter the year in the format YYYY/YYYY.",
                                regex="^\\d{4}/\\d{4}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
                ("TextBook_file", models.FileField(upload_to="resources/text-book/")),
                (
                    "Textbook_thumbnail",
                    models.ImageField(null=True, upload_to="resources/images/textbook"),
                ),
                ("Date_uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Topic", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
                ("Supervisor", models.CharField(max_length=100)),
                ("Project_file", models.FileField(upload_to="resources/project/")),
                (
                    "Project_thumbnail",
                    models.ImageField(null=True, upload_to="resources/images/project"),
                ),
                ("Date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "Session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.sessions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Exam Question", "Exam Question"),
                            ("Test Question", "Test Question"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Lecturer_name", models.CharField(max_length=100)),
                ("Course_name", models.CharField(max_length=100)),
                ("Course_code", models.CharField(max_length=100)),
                ("Course_file", models.FileField(upload_to="resources/past-question/")),
                (
                    "Course_image",
                    models.ImageField(
                        null=True, upload_to="resources/images/pastquestion"
                    ),
                ),
                ("Date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "Session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.sessions",
                    ),
                ),
            ],
        ),
    ]
