# Generated by Django 4.2.2 on 2023-07-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastquestion",
            old_name="Course_image",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Project_thumbnail",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="textbook",
            old_name="Textbook_thumbnail",
            new_name="thumbnail",
        ),
    ]
