# Generated by Django 4.2.2 on 2023-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastquestion",
            name="Session",
            field=models.DateField(),
        ),
    ]
