# Generated by Django 4.2.2 on 2023-07-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_rename_course_image_pastquestion_thumbnail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastquestion",
            old_name="Course_name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Topic",
            new_name="Name",
        ),
    ]
