# Generated by Django 4.2.2 on 2023-07-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_alter_pastquestion_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastquestion",
            name="Session",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter the year in the format YYYY/YYYY.",
                        regex="^\\d{4}/\\d{4}$",
                    )
                ],
            ),
        ),
    ]
