# Generated by Django 4.2.2 on 2023-07-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0003_rename_course_name_pastquestion_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastquestion",
            old_name="Course_file",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Project_file",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="textbook",
            old_name="TextBook_file",
            new_name="file",
        ),
    ]
