# Generated by Django 4.2.2 on 2023-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0004_alter_project_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastquestion",
            old_name="Course_title",
            new_name="Course_code",
        ),
        migrations.AddField(
            model_name="pastquestion",
            name="Type",
            field=models.CharField(
                choices=[
                    ("Exam Question", "Test Question"),
                    ("Exam Question", "Test Question"),
                ],
                default="Exam Question",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pastquestion",
            name="Course_image",
            field=models.ImageField(null=True, upload_to="media/resources/images"),
        ),
    ]
