# Generated by Django 4.2.2 on 2023-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0004_rename_course_file_pastquestion_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Type",
            field=models.CharField(default="Project", editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name="textbook",
            name="Type",
            field=models.CharField(default="Textbooks", editable=False, max_length=12),
        ),
    ]
