# Generated by Django 4.2.2 on 2023-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0005_rename_course_title_pastquestion_course_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastquestion",
            name="Type",
            field=models.CharField(
                choices=[
                    ("Exam Question", "Test Question"),
                    ("Exam Question", "Test Question"),
                ],
                max_length=50,
            ),
        ),
    ]
