# Generated by Django 4.2.2 on 2023-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0006_alter_pastquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastquestion",
            name="Course_file",
            field=models.FileField(upload_to="resources/past-question/"),
        ),
        migrations.AlterField(
            model_name="pastquestion",
            name="Course_image",
            field=models.ImageField(null=True, upload_to="resources/images"),
        ),
        migrations.AlterField(
            model_name="pastquestion",
            name="Type",
            field=models.CharField(
                choices=[
                    ("Exam Question", "Exam Question"),
                    ("Test Question", "Test Question"),
                ],
                max_length=50,
            ),
        ),
    ]
