# Generated by Django 4.2.2 on 2023-07-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0007_alter_pastquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastquestion",
            name="Type",
            field=models.CharField(
                choices=[
                    ("Exam_Questions", "Exam Questions"),
                    ("Text_Questions", "Text Questions"),
                ],
                max_length=50,
            ),
        ),
    ]
