# Generated by Django 4.2.2 on 2023-08-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0009_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="Resource_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
