# Generated by Django 4.2.2 on 2023-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
