# Generated by Django 4.2.2 on 2023-06-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_user_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
