# Generated by Django 4.2.2 on 2023-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
